### ISSUE TITLE
TypeError: 'WindowsPath' object is not iterable

### ISSUE THREAD

**Issue by zjrwtx** [gG8Fkpxq/BingLocalhost#2]
之前运行还是ok的，但现在不行了

![image](https://user-images.githubusercontent.com/86822589/233883900-5c78464a-95f8-431d-8941-13497a99374f.png)

**Comment by BlackSharkJ** [comment]
> 之前运行还是ok的，但现在不行了
> 
> ![image](https://user-images.githubusercontent.com/86822589/233883900-5c78464a-95f8-431d-8941-13497a99374f.png)

可能是你的cookieList这个变量出错了，执行`randowm.choice(cookieList)`时，这个变量必须是列表，而且列表的结构得是`List[WindosPath]`
如果你不希望它是列表，你得把这行代码改为：
```
cookieDict[IP] = [Chatbot(cookies), None]  # cookies: WindowsPath
```

**Comment by zjrwtx** [comment]
> > 之前运行还是ok的，但现在不行了
> > ![image](https://user-images.githubusercontent.com/86822589/233883900-5c78464a-95f8-431d-8941-13497a99374f.png)
> 
> 可能是你的cookieList这个变量出错了，执行`randowm.choice(cookieList)`时，这个变量必须是列表，而且列表的结构得是`List[WindosPath]` 如果你不希望它是列表，你得把这行代码改为：
> 
> ```
> cookieDict[IP] = [Chatbot(cookies), None]  # cookies: WindowsPath
> ```

谢谢，已解决
