### ISSUE TITLE
key error（是不是api的返回格式修改了）

### ISSUE THREAD

**Issue by zjrwtx** [gG8Fkpxq/BingLocalhost#3]
![image](https://user-images.githubusercontent.com/86822589/233985942-b9e2e165-08a7-4731-b81c-c9c011f8e208.png)

**Comment by BlackSharkJ** [comment]
我测试了一下，微软返回的数据格式没有发生变化，可能是您的网络问题。不过我刚刚更新了一下`main.py`。您可以下载新的试一试

**Comment by zjrwtx** [comment]
> 我测试了一下，微软返回的数据格式没有发生变化，可能是您的网络问题。不过我刚刚更新了一下`main.py`。您可以下载新的试一试

更新了，还是同样的问题，应该是提取的api返回格式问题，不同问题的话，api返回的json内容排序有时候不一样

**Comment by BlackSharkJ** [comment]
> > 我测试了一下，微软返回的数据格式没有发生变化，可能是您的网络问题。不过我刚刚更新了一下`main.py`。您可以下载新的试一试
> 
> 更新了，还是同样的问题，应该是提取的api返回格式问题，不同问题的话，api返回的json内容排序有时候不一样

可以告诉我您提的是什么问题吗？我测试一下

**Comment by zjrwtx** [comment]
> > > 我测试了一下，微软返回的数据格式没有发生变化，可能是您的网络问题。不过我刚刚更新了一下`main.py`。您可以下载新的试一试
> > 
> > 
> > 更新了，还是同样的问题，应该是提取的api返回格式问题，不同问题的话，api返回的json内容排序有时候不一样
> 
> 可以告诉我您提的是什么问题吗？我测试一下

我自己用那个edgegpt和fastapi做了一个api后端，测试到不同问题的返回内容有时候是变化的，然后gradio这个我现在试了一些问题经常显示找不到error：
![image](https://user-images.githubusercontent.com/86822589/234011627-fface3c0-d918-4a30-a350-d8f9231117b5.png)

**Comment by BlackSharkJ** [comment]
> > > > 我测试了一下，微软返回的数据格式没有发生变化，可能是您的网络问题。不过我刚刚更新了一下`main.py`。您可以下载新的试一试
> > > 
> > > 
> > > 更新了，还是同样的问题，应该是提取的api返回格式问题，不同问题的话，api返回的json内容排序有时候不一样
> > 
> > 
> > 可以告诉我您提的是什么问题吗？我测试一下
> 
> 我自己用那个edgegpt和fastapi做了一个api后端，测试到不同问题的返回内容有时候是变化的，然后gradio这个我现在试了一些问题经常显示找不到error： ![image](https://user-images.githubusercontent.com/86822589/234011627-fface3c0-d918-4a30-a350-d8f9231117b5.png)

就是“清华大学”这个问题吗？我自己试用了很多次，都没有出现你说的这个错误，微软返回的数据是会变化，但是数据结构都是大差不差的，关键的那几个key也没有改变，是不是你修改代码的时候对`quotes`这个变量没有处理好？你看看`main.py`的第48行：
```python
quotes = rs["item"]["messages"][1]["adaptiveCards"][0]["body"]
```
![2023-04-24 215247](https://user-images.githubusercontent.com/97328142/234017613-52da1bd2-3a39-45ea-b2fb-64f5ed56ab55.png)

**Comment by zjrwtx** [comment]
我删了原来的版本，重新换了你的最新版（然后只修改了cookiepath路径），还是同样的问题，但cmd日志显示是可以返回成功的：
![image](https://user-images.githubusercontent.com/86822589/234021139-31e5a122-5aab-40fe-b2be-241d96bf6a21.png)
![image](https://user-images.githubusercontent.com/86822589/234021351-0810decc-96a8-492c-b279-6c1210f62fe1.png)

**Comment by BlackSharkJ** [comment]
好吧，我仔细看了看您提供的截图，可能我们从微软获取的数据结构确实不一样，您的`rs["item"]["messages"][1]["adaptiveCards"][0]["body"]`比我的多嵌套了好几层，您可以根据微软返回的json修改一下这行代码和一直给您提示错误的那一行代码
```
quotes = rs["item"]["messages"][1]["adaptiveCards"][0]["body"]
```

**Comment by zjrwtx** [comment]
> 好吧，我仔细看了看您提供的截图，可能我们从微软获取的数据结构确实不一样，您的`rs["item"]["messages"][1]["adaptiveCards"][0]["body"]`比我的多嵌套了好几层，您可以根据微软返回的json修改一下这行代码和一直给您提示错误的那一行代码
> 
> ```
> quotes = rs["item"]["messages"][1]["adaptiveCards"][0]["body"]
> ```

好的 谢谢
